# Generated by Django 6.0.3 on 2026-04-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taremwa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('successful', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'indexes': [models.Index(fields=['username', '-attempted_at'], name='taremwa_log_usernam_eaa044_idx'), models.Index(fields=['ip_address', '-attempted_at'], name='taremwa_log_ip_addr_4f3cee_idx')],
            },
        ),
    ]
