# Generated by Django 6.0.3 on 2026-04-16 19:01

import taremwa.upload_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taremwa', '0002_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, storage=taremwa.upload_security.PrivateUploadStorage(), upload_to=taremwa.upload_security.avatar_upload_to),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='document',
            field=models.FileField(blank=True, storage=taremwa.upload_security.PrivateUploadStorage(), upload_to=taremwa.upload_security.document_upload_to),
        ),
    ]
